# Generated by Django 2.1.7 on 2019-03-18 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('preamble', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1500)),
                ('timestamp', models.DateTimeField(verbose_name='date_published')),
                ('author', models.ForeignKey(limit_choices_to={'groups__name': 'course_coordinators'}, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
