# Generated by Django 2.1.7 on 2019-03-20 16:56

import communications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, upload_to=communications.models.get_avatar_image_path),
        ),
    ]
