image: python:latest

before_script:
  - pip install -r requirements.txt

test:
  script:
  - coverage run --source='.' manage.py test
  - coverage report --skip-covered | grep TOTAL
  artifacts:
    paths:
      - coverage_html_report
