# Generated by Django 2.0.12 on 2019-02-11 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('subject_code', models.CharField(max_length=10, unique=True)),
                ('assistant', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'assistants'}, related_name='courses_assisting_in', to=settings.AUTH_USER_MODEL)),
                ('course_coordinator', models.OneToOneField(default=None, limit_choices_to={'groups__name': 'course_coordinators'}, on_delete=django.db.models.deletion.CASCADE, related_name='course', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'students'}, related_name='courses_enrolled_in', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
