# Generated by Django 2.1.6 on 2019-02-11 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('emneansvarlig', models.ForeignKey(default=0, limit_choices_to={'groups__name': 'emne_ansvarlig'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('studasser', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'studass'}, related_name='studasser', to=settings.AUTH_USER_MODEL)),
                ('studenter', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'student'}, related_name='studenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
