# Generated by Django 2.1.7 on 2019-03-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationinterval',
            options={'ordering': ['booking_interval__day']},
        ),
    ]
