# Generated by Django 2.1.7 on 2019-02-27 15:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant', models.ForeignKey(limit_choices_to={'groups__name': 'assistants'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bookinginterval',
            name='min_available_assistants',
        ),
        migrations.AddField(
            model_name='bookinginterval',
            name='max_available_assistants',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bookinginterval',
            name='assistants',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'assistants'}, related_name='setup_booking_intervals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_coordinator',
            field=models.OneToOneField(blank=True, limit_choices_to={'groups__name': 'course_coordinators'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervising_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservationinterval',
            name='booking_interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_intervals', to='booking.BookingInterval'),
        ),
        migrations.AddField(
            model_name='reservationconnection',
            name='reservation_interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='booking.ReservationInterval'),
        ),
        migrations.AddField(
            model_name='reservationconnection',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'students'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
