# Generated by Django 2.1.7 on 2019-02-25 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_auto_20190224_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant', models.ForeignKey(limit_choices_to={'groups__name': 'assistants'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('booking_interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.BookingInterval')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='assistant',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='booking_interval',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='student',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.AddField(
            model_name='reservationconnection',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='booking.ReservationInterval'),
        ),
        migrations.AddField(
            model_name='reservationconnection',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'students'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
