# Generated by Django 2.0.12 on 2019-02-14 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_auto_20190211_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInterval',
            fields=[
                ('day', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday')], max_length=20)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('min_available_assistants', models.IntegerField(blank=True, default=0, null=True)),
                ('nk', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('assistants', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'assistants'}, related_name='setup_assistant_hours', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_interval', to='booking.Course')),
            ],
        ),
    ]
