# Generated by Django 2.1.7 on 2019-02-24 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginterval',
            name='assistants',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'assistants'}, related_name='setup_booking_intervals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_coordinator',
            field=models.OneToOneField(blank=True, limit_choices_to={'groups__name': 'course_coordinators'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervising_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='index',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]),
        ),
    ]
