# Generated by Django 2.1.7 on 2019-03-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190314_1229'),
        ('booking', '0002_auto_20190318_1447'),
    ]

    operations = [
    ]
