# Generated by Django 2.1.7 on 2019-02-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190225_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationinterval',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservationinterval',
            name='booking_interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_intervals', to='booking.BookingInterval'),
        ),
    ]
