# Generated by Django 2.1.7 on 2019-02-27 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190227_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginterval',
            name='min_available_assistants',
        ),
        migrations.AddField(
            model_name='bookinginterval',
            name='max_available_assistants',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
