# Generated by Django 2.1.7 on 2019-02-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20190227_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationconnection',
            old_name='reservation',
            new_name='reservation_interval',
        ),
    ]
