# Generated by Django 2.1.7 on 2019-03-08 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='review_text',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'assisting_courses': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='booking.Course'), 'supervising_course': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='booking.Course')}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
